# -*- coding: utf-8 -*-
"""FizzBuzz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zKfPRg5fVINRUSOpQSfTTohvCTiY_d9r
"""

#FizzBuzz
#Python

#いくつまでするか聞く
x = float(input("いくつまで数えますか"))

#整数かチェック
if x % 1 == 0:
#指定回数繰り返す
    for i in range(1,int(x)+1):
    #3と5で割れるとき
        if i % 3 == 0 and i % 5 == 0:
            print("FizzBuzz")
    #3で割れるとき
        elif i % 3 ==0:
            print("Fizz")
    #5で割れるとき
        elif i % 5 == 0:
            print("Buzz")
    #それ以外
        else:
            print(i)
else:
    print("整数を入力してください")